---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  #product_version: 13.6.4

verifier:
  name: inspec

platforms:
#- name: windows2016
#  driver_config:
#      box: jacqinthebox/windowsserver2016
#      box_url: https://app.vagrantup.com/jacqinthebox/boxes/windowsserver2016

- name: windows-2012r2
  driver_config:
      box: mwrock/Windows2012R2
      box_url: https://app.vagrantup.com/mwrock/Windows2012R2


suites:
  - name: default
    run_list:
     - recipe[nrhl_iis::default]

    attributes:
